MED-449-Added no of instances as argument
teamclairvoyant/nextflow-python-automation pull request #3
Opened 2023-04-07 21:21 UTC by harshal359

2023-04-08 22:23 UTC, rssanders3 requested changes
Missing the MAP we discussed with the other M series ec2 instances and their corresponding cpus.

2023-04-10 15:45 UTC, rssanders3 requested changes

2023-04-10 15:45 UTC, rssanders3 commented on nextflow_aws_batch_trigger.py
> +    instances = {
MIssing the other m5 series. Add all. And set this as a global variable in the code.

2023-04-10 22:27 UTC, rssanders3 approved these changes

2023-04-11 15:33 UTC, jastidinesh approved these changes

2023-04-11 15:39 UTC, merged